apiVersion: v1
kind: Pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - db
  containers:
  - args:
    - --max_connections=1200
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_PASSWORD
      value: odoo
    - name: POSTGRES_USER
      value: odoo
    image: postgres:12
    imagePullPolicy: IfNotPresent
    name: db-bukka
    resources:
      limits:
        cpu: "1"
        memory: 6000Mi
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: vol-ytjxx
      subPath: database
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r6kkj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vmi1147231
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: db-bukka
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: dshm
  - name: vol-ytjxx
    persistentVolumeClaim:
      claimName: bukka
  - name: kube-api-access-r6kkj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:31:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:32:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:32:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:31:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://df8444b4cea9d49f09db0020dfc343ea0d20d679d19822cf1d3832b4596e6621
    image: postgres:12
    imageID: docker-pullable://postgres@sha256:a3ab8b0405a0d2257dbac999638f5a1b20709946f2ee207c878797cbdf503eb7
    lastState: {}
    name: db-bukka
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-14T14:32:01Z"
  hostIP: 86.48.0.19
  phase: Running
  podIP: 10.42.3.250
  podIPs:
  - ip: 10.42.3.250
  qosClass: Burstable
  startTime: "2023-03-14T14:31:58Z"
