apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: odoo-pop
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: default
spec:
  behavior:
#    scaleDown:
#      policies:
#        - type: string
#          periodSeconds: int
#          value: int
#      selectPolicy: string
#      stabilizationWindowSeconds: int
#    scaleUp:
#      policies:
#        - type: string
#          periodSeconds: int
#          value: int
#      selectPolicy: string
#      stabilizationWindowSeconds: int
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
#    - type: string
#      containerResource:
#        container: string
#        name: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      external:
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      object:
#        describedObject:
#          apiVersion: string
#          kind: string
#          name: string
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      pods:
#        metric:
#          name: string
#          selector:
#            matchExpressions:
#              - key: string
#                operator: string
#                values:
#                  - string
#            matchLabels:  key: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
#      resource:
#        name: string
#        target:
#          type: string
#          averageUtilization: int
#          averageValue: string
#          value: string
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: odoo-pop