apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-cnet2
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 'odoo-cnet2.209.145.58.65'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-cnet2
            port:
              name: http
  tls:
  - hosts:
    - 'odoo-cnet2.209.145.58.65'
    secretName: 'odoo-cnet2.209.145.58.65-tls'
