apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: odoo-cnet2 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi


apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-cnet2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"