apiVersion: v1
kind: Service
metadata:
  annotations:
    name: db-lighthouse
spec:
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-default-db-lighthouse
  ports:
    - protocol: TCP
      targetPort: 42
      port: 42
      name: db-lighthouse