apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-evoucherng
  labels:
    app: odoo-evoucherng
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
