apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-silverflowca
  labels:
    app: odoo-silverflowca
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
