apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-eliteboxng
  labels:
    app: odoo-eliteboxng
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
