apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-lighthouse
  labels:
    app: odoo-lighthouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
