apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-harvesthouse
  labels:
    app: odoo-harvesthouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
