apiVersion: v1
kind: Service
metadata:
  name: odoo-basic-app
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-basic-app
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http