apiVersion: v1
kind: Service
metadata:
  name: odoo-bukka
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-bukka
  ports:
    - protocol: TCP
      targetPort: odoo-bukka
      port: 8069
      name: odoo-bukka

apiVersion: v1
kind: Service
metadata:
  name: db-bukka
spec:
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-default-db-bukka
  ports:
    - protocol: TCP
      targetPort: db-bukka
      port: 42
      name: db-bukka