apiVersion: v1
kind: Service
metadata:
  name: odoo-bukka-stag
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-bukka-stag
  ports:
    - protocol: TCP
      targetPort: odoo-bukka-stag
      port: 8069
      name: odoo-bukka-stag