apiVersion: v1
kind: Service
metadata:
  name: odoo-helptest
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-helptest
  ports:
    - protocol: TCP
      targetPort: odoo-helptest
      port: 8069
      name: odoo-helptest