apiVersion: v1
kind: Service
metadata:
  name: odoo-fbds
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-fbds
  ports:
    - protocol: TCP
      targetPort: odoo-fbds
      port: 8069
      name: odoo-fbds