apiVersion: v1
kind: Service
metadata:
  name: odoo-lighthouse
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-lighthouse
  ports:
    - protocol: TCP
      targetPort: odoo-lighthouse
      port: 8069
      name: odoo-lighthouse