apiVersion: v1
kind: Service
metadata:
  name: odoo-eliteboxng
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-eliteboxng
  ports:
    - protocol: TCP
      targetPort: odoo-eliteboxng
      port: 8069
      name: odoo-eliteboxng