apiVersion: v1
kind: Service
metadata:
  name: odoo-rec
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-odoo-rec
  ports:
    - protocol: TCP
      targetPort: odoo-rec
      port: 8069
      name: odoo-rec