apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: main-splunk
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-12T22:56:03Z"
  labels:
    app.kubernetes.io/instance: main-splunk
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/version: 2.2.0
    control-plane: controller-manager
    helm.sh/chart: splunk-operator-2.2.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:control-plane: {}
          f:helm.sh/chart: {}
    manager: helm
    operation: Update
    time: "2023-03-12T22:56:03Z"
  name: splunk-operator-controller-manager
  namespace: default
