apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: main-splunk
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-12T20:17:53Z"
  labels:
    app.kubernetes.io/instance: main-splunk
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/version: 2.2.0
    control-plane: controller-manager
    helm.sh/chart: splunk-operator-2.2.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:control-plane: {}
          f:helm.sh/chart: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: helm
    operation: Update
    time: "2023-03-12T20:17:53Z"
  name: splunk-operator-controller-manager-metrics-service
  namespace: default
spec:
  clusterIP: 10.43.32.242
  clusterIPs:
  - 10.43.32.242
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: main-splunk
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/version: 2.2.0
    control-plane: controller-manager
    helm.sh/chart: splunk-operator-2.2.0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
