apiVersion: v1
kind: Service
metadata:
  name: splunk-truck
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-splunk-truck
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http