apiVersion: v1
kind: Service
metadata:
  name: sswss-odoo
  namespace: sswss-odoo
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-sswss-odoo
  ports:
    - protocol: TCP
      targetPort: sswss-odoo
      port: 8069
      name: sswss-odoo
