apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-atlantic
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    objectset.rio.cattle.io/hash: dbb408b909497414f93be5e7a78a2f285d27b7e1
    workload.user.cattle.io/workloadselector: statefulSet-default-db-atlantic
  name: db-atlantic
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-default-db-atlantic
  serviceName: db-atlantic
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-04T02:49:36Z"
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-default-db-atlantic
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - db
      containers:
      - args:
        - -c
        - max_connections=1200
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        image: postgres:12
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - exec pg_isready -U "odoo" -d "dbname=postgres" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: db-atlantic
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - exec pg_isready -U "odoo" -d "dbname=postgres" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 6000Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        # Edit the volume to match the existing volumeMounts in the cluster
        - mountPath: /var/lib/postgresql/data
          name: vol-ytjxx
          subPath: database
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      # Edit the volume to match the existing pv in the cluster
      - name: vol-ytjxx
        persistentVolumeClaim:
          claimName: odoo-atlantic
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 1
  replicas: 1
