apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2023-01-21T16:31:16Z"
    cni.projectcalico.org/containerID: 735bd289ff82c14fa791f50ac3f68cc06710a21017de14da2866e269e30e0ec2
    cni.projectcalico.org/podIP: 10.42.3.250/32
    cni.projectcalico.org/podIPs: 10.42.3.250/32
    field.cattle.io/ports: '[[]]'
  creationTimestamp: "2023-03-14T14:31:58Z"
  generateName: db-bukka-
  labels:
    controller-revision-hash: db-bukka-6f9c97cc68
    workload.user.cattle.io/workloadselector: statefulSet-default-db-bukka
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cattle.io/timestamp: {}
          f:field.cattle.io/ports: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"d136565c-b478-49ea-9e0f-f5d36e00195b"}: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution: {}
        f:containers:
          k:{"name":"db-bukka"}:
            .: {}
            f:args: {}
            f:env:
              .: {}
              k:{"name":"POSTGRES_DB"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POSTGRES_PASSWORD"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POSTGRES_USER"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities: {}
              f:privileged: {}
              f:readOnlyRootFilesystem: {}
              f:runAsNonRoot: {}
            f:stdin: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:tty: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/var/lib/postgresql/data"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"dshm"}:
            .: {}
            f:emptyDir:
              .: {}
              f:medium: {}
            f:name: {}
          k:{"name":"vol-ytjxx"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-03-14T14:31:58Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cni.projectcalico.org/containerID: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    subresource: status
    time: "2023-03-14T14:32:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.42.3.250"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2023-03-14T14:32:01Z"
  namespace: default
  esourceVersion: "35569901"
  uid: c7ba2039-afe1-4656-9628-fca7575ae0e8
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - db
  containers:
  - args:
    - --max_connections=1200
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_PASSWORD
      value: odoo
    - name: POSTGRES_USER
      value: odoo
    image: postgres:12
    imagePullPolicy: IfNotPresent
    name: db-bukka
    resources:
      limits:
        cpu: "1"
        memory: 6000Mi
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: vol-ytjxx
      subPath: database
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r6kkj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vmi1147231
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: db-bukka
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: dshm
  - name: vol-ytjxx
    persistentVolumeClaim:
      claimName: bukka
  - name: kube-api-access-r6kkj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:31:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:32:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:32:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-14T14:31:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://df8444b4cea9d49f09db0020dfc343ea0d20d679d19822cf1d3832b4596e6621
    image: postgres:12
    imageID: docker-pullable://postgres@sha256:a3ab8b0405a0d2257dbac999638f5a1b20709946f2ee207c878797cbdf503eb7
    lastState: {}
    name: db-bukka
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-14T14:32:01Z"
  hostIP: 86.48.0.19
  phase: Running
  podIP: 10.42.3.250
  podIPs:
  - ip: 10.42.3.250
  qosClass: Burstable
  startTime: "2023-03-14T14:31:58Z"
