apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-basic
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    objectset.rio.cattle.io/hash: dbb408b909497414f93be5e7a78a2f285d27b7e1
    workload.user.cattle.io/workloadselector: statefulSet-default-db-basic
  name: db-basic
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-default-db-basic
  serviceName: db-basic
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-04T02:49:36Z"
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-default-db-basic
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - db
      containers:
      - args:
        - -c
        - max_connections=1200
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        image: postgres:12
        imagePullPolicy: IfNotPresent
        name: db-basic
        resources:
          limits:
            cpu: "1"
            memory: 6000Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        # Edit the volume to match the existing volumeMounts in the cluster
        - mountPath: /var/lib/postgresql/data
          name: vol-ytjxx
          subPath: database16
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      # Edit the volume to match the existing pv in the cluster
      - name: vol-ytjxx
        persistentVolumeClaim:
          claimName: pvc-e757b8ba-5c5c-4982-9b65-07ec72e0edbe
      - configMap:
          defaultMode: 511
          name: postgresql.conf
          optional: true
        name: config
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 1
  replicas: 1
