apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-bip
    app.kubernetes.io/managed-by: Helm
    cattle.io/creator: norman
    objectset.rio.cattle.io/hash: dbb408b909497414f93be5e7a78a2f285d27b7e1
    workload.user.cattle.io/workloadselector: statefulSet-default-db-bip
  name: db-bip
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-default-db-bip
  serviceName: db-bip
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-09-04T02:49:36Z"
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-default-db-bip
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: stack
                operator: In
                values:
                - db
      containers:
      - args:
        - --max_connections=200
        - --shared_buffers=1072MB
        - --work_mem=1GB
        - --dynamic_shared_memory_type=posix
        - --maintenance_work_mem=1GB
        - --max_wal_size=1GB
        - --min_wal_size=1GB
        - --checkpoint_completion_target=0.9
        - --effective_cache_size=1GB
        - --max_parallel_workers_per_gather=8
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        image: postgres:15
        imagePullPolicy: IfNotPresent
        name: db-bip
        
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        # Edit the volume to match the existing volumeMounts in the cluster
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /var/lib/postgresql/data
          name: vol-ytjxx
          subPath: database
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: stack
        operator: Equal
        value: db
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dshm
      # Edit the volume to match the existing pv in the cluster
      - name: vol-ytjxx
        persistentVolumeClaim:
          claimName: odoo-bip
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 1
  replicas: 1
