apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo-helptest
    tier: frontend
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-odoo-helptest
  name: odoo-helptest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-odoo-helptest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-09T18:59:34Z"
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-odoo-helptest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - files
      containers:
      - env:
        - name: HOST
          value: db-basic
        - name: PASSWORD
          value: odoo
        - name: USER
          value: odoo
        image: odoo:13
        imagePullPolicy: IfNotPresent
        name: odoo-helptest
        resources:
          limits:
            cpu: "1"
            memory: 6000Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        ports:
            - containerPort: 8069
              name: odoo-helptest
              protocol: TCP
        volumeMounts:
        # Edit the volume to match the existing mountPaths in the cluster
        - mountPath: /etc/odoo
          name: config
        - mountPath: /var/lib/odoo
          name: vol-7xe3r
          subPath: odoo13
        - mountPath: /mnt/extra-addons
          name: vol-xjnem
          subPath: odoo/addons
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 509
          name: odoo.conf
          optional: true
        name: config
      # Edit the volume to match the existing pv in the cluster
      - name: vol-7xe3r
        persistentVolumeClaim:
          claimName: pvc-35b715b7-f277-4025-9b8a-7a0d012a88ae
      - name: vol-xjnem
        persistentVolumeClaim:
          claimName: tbv-odoo-d

