apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo-setfree
    tier: frontend
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-odoo-setfree
  name: odoo-setfree
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-odoo-setfree
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-odoo-setfree
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - until pg_isready -h db-setfree -p 5432; do echo waiting for datasetfree; sleep
          2; done;
        image: postgres:9.6.5
        imagePullPolicy: IfNotPresent
        name: check-db-ready
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - 'if psql -h db-setfree -U odoo -p 5432 -lqt | cut -d \| -f 1 | grep -qw "setfree";
          then echo "The datasetfree setfree exists." else until createdb -h db-setfree
          -U odoo -p 5432 setfree; fi '
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: PGPASSWORD
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        image: postgres:9.6.5
        imagePullPolicy: IfNotPresent
        name: db-install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - |
          FTP_HOST="ss.vps50988.mylogin.co"
          FTP_USER="odoo_ss.vps50988.mylogin.co"
          FTP_PASSWORD="i24125114A"
          FTP_REMOTE_FILE="dump.sql"
          FTP_REMOTE_FILESTORE="odoo17-basic.zip"
          LOCAL_HOST="db-setfree"
          LOCAL_USER="odoo"
          LOCAL_DATAsetfree="setfree"
          LOCAL_DUMP_FILE="odoo17-basic.zip"

          echo "Entering odoo directory...."
          cd /mnt/
          echo "Creating filestore directory..."
          mkdir filestore
          mkdir addons
          echo "Creating $LOCAL_DATAsetfree directory..."
          mkdir filestore/$LOCAL_DATAsetfree
          echo "Downloading filestore files..."
          cd addons/
          wget -P ./ "ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST/$FTP_REMOTE_FILESTORE"
          echo "Extracting archive..."
          unzip $LOCAL_DUMP_FILE
          echo "Move files from directory"
          mv filestore/* /mnt/filestore/$LOCAL_DATAsetfree
          mv dump.sql /mnt/
          echo "List items in odoo directory..."
          ls /mnt/
          echo "List contents in filestore directory..."
          ls /mnt/filestore/$LOCAL_DATAsetfree/

          echo "Setting directory permissions..."
          chmod -Rv 777 /mnt/filestore
          echo "Permissions set..."
            
        #  fi
        image: busybox
        imagePullPolicy: IfNotPresent
        name: filestore-restored
        volumeMounts:
        # Edit the volume to match the existing mountPaths in the cluster
        - mountPath: /mnt
          name: vol-7xe3r
          subPath: odoo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - |
          LOCAL_HOST="db-setfree"
          LOCAL_USER="odoo"
          LOCAL_DATAsetfree="setfree"
          LOCAL_DUMP_FILE="odoo-basic.dump"

          if ! PGPASSWORD="odoo" psql -h db-setfree -U odoo -d setfree -c "SELECT 1 FROM information_schema.tables WHERE table_name = 'res_users'" | grep -q 1; then
            echo "The res_users table doesn't exist in the setfree datasetfree. Proceeding with datasetfree restore..."

            echo "Entering odoo directory..."
            cd /var/lib/odoo/addons/
            echo "List contents of odoo directory..."
            ls /var/lib/odoo/addons/

            echo "Restoring datasetfree dump locally..."
            if PGPASSWORD="odoo" createdb -h "$LOCAL_HOST" -U "$LOCAL_USER" -e "$LOCAL_DATAsetfree"; then
              echo "The datasetfree $LOCAL_DATAsetfree created..."
            else echo "The datasetfree $LOCAL_DATAsetfree already exists..."
            fi
            if PGPASSWORD="odoo" pg_restore -h "$LOCAL_HOST" -U "$LOCAL_USER" -d "$LOCAL_DATAsetfree" -v "$LOCAL_DUMP_FILE"; then
                 
                 echo "Datasetfree restored successfully."
                 rm "$LOCAL_DUMP_FILE"
              else  echo "Datasetfree failed to be restored."
                    rm "$LOCAL_DUMP_FILE"
              fi
          else
            echo "The res_users table already exists in the setfree datasetfree. Skipping datasetfree restore."
          fi
        image: odoo:17
        imagePullPolicy: IfNotPresent
        name: db-restored
        volumeMounts:
        # Edit the volume to match the existing mountPaths in the cluster
        - mountPath: /var/lib/odoo
          name: vol-7xe3r
          subPath: odoo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: stack
                operator: In
                values:
                - odoo
      containers:
      - env:
        - name: HOST
          value: db-setfree
        - name: PASSWORD
          value: odoo
        - name: USER
          value: odoo
        image: odoo:17
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /web/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 600
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8069
          name: http
          protocol: TCP
        startupProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              path: /web/health
              port: http
              scheme: HTTP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /web/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 5
        name: odoo-setfree
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        ports:
            - containerPort: 8069
              name: http
              protocol: TCP
        volumeMounts:
        # Edit the volume to match the existing mountPaths in the cluster
        - mountPath: /var/lib/odoo
          name: vol-7xe3r
          subPath: odoo
        - mountPath: /mnt/extra-addons
          name: vol-7xe3r
          subPath: odoo/addons
        - mountPath: /etc/odoo
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 509
          name: odoo-setfree.conf
          optional: true
        name: config
      # Edit the volume to match the existing pv in the cluster
      - name: vol-7xe3r
        persistentVolumeClaim:
          claimName: odoo-setfree

