apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-studio24-app
  annotations:
    # cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # ingressClassName: nginx
  rules:
  - host: www.studio24nigeria.com
    http:
      paths:
      - path: /web#(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: odoo-studio24-app
            port:
              name: http
  - host: odoo-studio24.webdiscode.com
    http:
      paths:
      - path: /web#(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: odoo-studio24-app
            port:
              name: http
  tls:
  - hosts:
    - www.studio24nigeria.com
    secretName: www.studio24nigeria.com-tls
  - hosts:
    - odoo-studio24.webdiscode.com
    secretName: odoo-studio24.webdiscode.com-tls
