apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splunk-truck
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: splunk-truck.webdiscode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk-truck
            port:
              name: http
  tls:
  - hosts:
    - splunk-truck.webdiscode.com
    secretName: splunk-truck.webdiscode.com-tls
