apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evoucher-odoo
  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: evoucher-odoo.webdiscode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evoucher-odoo
            port:
              number: 8069
