apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odoo-pop
    tier: frontend
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-odoo-pop
  name: odoo-pop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-odoo-pop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-odoo-pop
    spec:
      initContainers:
      - name: wait-for-db-table
        image: postgres:13
        command:
        - sh
        - -c
        - |
          LOCAL_HOST="db-pop"
          LOCAL_USER="odoo"
          LOCAL_DATABASE="pop"
          LOCAL_DUMP_FILE="odoo-basic.dump"
          while true; do
            if PGPASSWORD="odoo" psql -h $LOCAL_HOST -U $LOCAL_USER -d $LOCAL_DATABASE -c "SELECT 1 FROM information_schema.tables WHERE table_name = 'res_users'" | grep -q 1; then
              echo "The res_users table exists in the pop database. Proceeding to start the main container."
              break
            else
              echo "The res_users table doesn't exist in the pop database. Proceeding with database restore..."
              
              echo "Entering odoo directory..."
              cd /var/lib/odoo/addons/
              echo "List contents of odoo directory..."
              ls /var/lib/odoo/addons/

              echo "Restoring database dump locally..."
              if PGPASSWORD="odoo" createdb -h "$LOCAL_HOST" -U "$LOCAL_USER" -e "$LOCAL_DATABASE"; then
                echo "The database $LOCAL_DATABASE created..."
              else
                echo "The database $LOCAL_DATABASE already exists..."
              fi

              if PGPASSWORD="odoo" pg_restore -h "$LOCAL_HOST" -U "$LOCAL_USER" -d "$LOCAL_DATABASE" -v "$LOCAL_DUMP_FILE"; then
                echo "Database restored successfully."
                rm "$LOCAL_DUMP_FILE"
                break
              else
                echo "Database failed to be restored. Retrying in 5 minutes..."
                rm "$LOCAL_DUMP_FILE"
                sleep 300
              fi
            fi
          done
      # - command:
      #   - sh
      #   - -c
      #   - until pg_isready -h db-pop -p 5432; do echo waiting for database; sleep
      #     2; done;
      #   image: postgres:9.6.5
      #   imagePullPolicy: IfNotPresent
      #   name: check-db-ready
      #   resources: {}
      #   terminationMessagePath: /dev/termination-log
      #   terminationMessagePolicy: File
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: stack
                operator: In
                values:
                - db
      containers:
      - env:
        - name: HOST
          value: db-pop
        - name: PASSWORD
          value: odoo
        - name: USER
          value: odoo
        image: odoo:17
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /web/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 600
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8069
          name: http
          protocol: TCP
        startupProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              path: /web/health
              port: http
              scheme: HTTP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /web/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 5
        name: odoo-pop
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        ports:
            - containerPort: 8069
              name: http
              protocol: TCP
        volumeMounts:
        # Edit the volume to match the existing mountPaths in the cluster
        - mountPath: /var/lib/odoo
          name: vol-7xe3r
          subPath: odoo
        - mountPath: /mnt/extra-addons
          name: vol-7xe3r
          subPath: odoo/addons
        - mountPath: /etc/odoo
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 509
          name: odoo-pop.conf
          optional: true
        name: config
      # Edit the volume to match the existing pv in the cluster
      - name: vol-7xe3r
        persistentVolumeClaim:
          claimName: odoo-pop

