apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-atlantic
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: w3.atlanticgunsandgear.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-atlantic
            port:
              name: http
  tls:
  - hosts:
    - www.atlanticgunsandgear.com
    secretName: www.atlanticgunsandgear.com-tls
