apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-agg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: agg.webdiscode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-agg
            port:
              number: 8069
  - host: 202.webdiscode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-agg
            port:
              number: 8069
