apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-cnet5
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: odoo-cnet5
            port:
              name: http
    # host: cnet.webdiscode.com
    
  # tls:
  # - hosts:
  #   - cnet.webdiscode.com
  #   secretName: cnet.webdiscode.com-tls
