version: '3'
services:
    # Etherpad: real-time collaborative document editing
    db:
        image: mysql:5.7
        restart: ${RESTART_POLICY}
        environment:
            - MYSQL_DATABASE=etherpad_lite_db
            - MYSQL_PASSWORD=CHANGEME
            - MYSQL_USER=etherpaduser
        volumes:
            - ./etherpad/db/mysql/data:/var/lib/mysql
            - ./etherpad/db/mysql/init:/docker-entrypoint-initdb.d/:ro
        networks:
            - meet.jitsi
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    etherpad:
        image: etherpad/etherpad:1.8.6
        restart: ${RESTART_POLICY}
        environment:
            - TITLE=${ETHERPAD_TITLE}
            - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
            - SKIN_NAME=${ETHERPAD_SKIN_NAME}
            - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
            - DB_TYPE=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_NAME=etherpad_lite_db
            - DB_USER=etherpaduser
            - DB_PASS=CHANGEME
            - DB_CHARSET=utf8mb4
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
        ports:
            - 9001:9001
