apiVersion: v1
kind: Service
metadata:
  name: odoo-retail
  labels:
    app: odoo-retail
spec:
  ports:
  - name: 8069tcp01
    port: 8069
    protocol: TCP
    targetPort: 8069
  selector:
    app: odoo-retail
    tier: frontend
  type: NodePort
