apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    field.cattle.io/creatorId: user-t5wpm
    field.cattle.io/publicEndpoints: '[{"addresses":["159.89.12.95"],"port":31326,"protocol":"TCP","serviceName":"default:odoo-nodeport","allNodes":true},{"addresses":["159.89.12.95"],"port":443,"protocol":"HTTPS","serviceName":"default:odoo-nodeport","ingressName":"default:prints","hostname":"prints.studio24nigeria.com","allNodes":true},{"addresses":["159.89.12.95"],"port":443,"protocol":"HTTPS","serviceName":"default:odoo-nodeport","ingressName":"default:studio24nigeria","hostname":"www.studio24nigeria.com","allNodes":true},{"addresses":["159.89.12.95"],"port":443,"protocol":"HTTPS","serviceName":"default:odoo-nodeport","ingressName":"default:erp","hostname":"erp.studio24nigeria.com","allNodes":true}]'
  creationTimestamp: "2021-10-14T10:08:19Z"
  generation: 41
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-odoo
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"odoo"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"HOST"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8069,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/mnt/extra-addons"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/lib/odoo"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"vol1"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
              k:{"name":"vol2"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                  f:optional: {}
                f:name: {}
              k:{"name":"vol3"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
    manager: rancher
    operation: Update
    time: "2021-11-06T22:39:26Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-11-06T22:39:29Z"
  name: odoo
  namespace: default
  resourceVersion: "15961429"
  uid: 57eb8973-592c-4687-99c1-94f8e87aeb38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-odoo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-06T22:39:24Z"
        field.cattle.io/ports: '[[{"containerPort":8069,"dnsName":"odoo-nodeport","hostPort":0,"kind":"NodePort","name":"8069tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-odoo
    spec:
      containers:
      - env:
        - name: HOST
          value: db
        - name: PASSWORD
          value: odoo
        - name: USER
          value: odoo
        image: odoo:15
        imagePullPolicy: Always
        name: odoo
        ports:
        - containerPort: 8069
          name: 8069tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/odoo
          name: vol1
        - mountPath: /mnt/extra-addons
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/staging/odoo
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /mnt/data/extra-addons
          type: DirectoryOrCreate
        name: vol3
      - configMap:
          defaultMode: 509
          name: odoo
          optional: false
        name: vol2
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-17T21:45:29Z"
    lastUpdateTime: "2021-10-17T21:45:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-14T10:08:20Z"
    lastUpdateTime: "2021-11-06T22:39:29Z"
    message: ReplicaSet "odoo-57c8dd8b96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 41
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
